// countries.js — données complètes pour GeoQuiz
// ISO 3166-1 alpha-2 codes, noms FR/EN/DE, continents

export const COUNTRIES = [
    { iso: "af", fr: "Afghanistan", en: "Afghanistan", de: "Afghanistan", continent: "AS" },
    { iso: "al", fr: "Albanie", en: "Albania", de: "Albanien", continent: "EU" },
    { iso: "dz", fr: "Algérie", en: "Algeria", de: "Algerien", continent: "AF" },
    { iso: "ad", fr: "Andorre", en: "Andorra", de: "Andorra", continent: "EU" },
    { iso: "ao", fr: "Angola", en: "Angola", de: "Angola", continent: "AF" },
    { iso: "ag", fr: "Antigua-et-Barbuda", en: "Antigua and Barbuda", de: "Antigua und Barbuda", continent: "NA" },
    { iso: "ar", fr: "Argentine", en: "Argentina", de: "Argentinien", continent: "SA" },
    { iso: "am", fr: "Arménie", en: "Armenia", de: "Armenien", continent: "AS" },
    { iso: "au", fr: "Australie", en: "Australia", de: "Australien", continent: "OC" },
    { iso: "at", fr: "Autriche", en: "Austria", de: "Österreich", continent: "EU" },
    { iso: "az", fr: "Azerbaïdjan", en: "Azerbaijan", de: "Aserbaidschan", continent: "AS" },
    { iso: "bs", fr: "Bahamas", en: "Bahamas", de: "Bahamas", continent: "NA" },
    { iso: "bh", fr: "Bahreïn", en: "Bahrain", de: "Bahrain", continent: "AS" },
    { iso: "bd", fr: "Bangladesh", en: "Bangladesh", de: "Bangladesch", continent: "AS" },
    { iso: "bb", fr: "Barbade", en: "Barbados", de: "Barbados", continent: "NA" },
    { iso: "by", fr: "Biélorussie", en: "Belarus", de: "Belarus", continent: "EU" },
    { iso: "be", fr: "Belgique", en: "Belgium", de: "Belgien", continent: "EU" },
    { iso: "bz", fr: "Belize", en: "Belize", de: "Belize", continent: "NA" },
    { iso: "bj", fr: "Bénin", en: "Benin", de: "Benin", continent: "AF" },
    { iso: "bt", fr: "Bhoutan", en: "Bhutan", de: "Bhutan", continent: "AS" },
    { iso: "bo", fr: "Bolivie", en: "Bolivia", de: "Bolivien", continent: "SA" },
    { iso: "ba", fr: "Bosnie-Herzégovine", en: "Bosnia and Herzegovina", de: "Bosnien und Herzegowina", continent: "EU" },
    { iso: "bw", fr: "Botswana", en: "Botswana", de: "Botswana", continent: "AF" },
    { iso: "br", fr: "Brésil", en: "Brazil", de: "Brasilien", continent: "SA" },
    { iso: "bn", fr: "Brunei", en: "Brunei", de: "Brunei", continent: "AS" },
    { iso: "bg", fr: "Bulgarie", en: "Bulgaria", de: "Bulgarien", continent: "EU" },
    { iso: "bf", fr: "Burkina Faso", en: "Burkina Faso", de: "Burkina Faso", continent: "AF" },
    { iso: "bi", fr: "Burundi", en: "Burundi", de: "Burundi", continent: "AF" },
    { iso: "cv", fr: "Cap-Vert", en: "Cape Verde", de: "Kap Verde", continent: "AF" },
    { iso: "kh", fr: "Cambodge", en: "Cambodia", de: "Kambodscha", continent: "AS" },
    { iso: "cm", fr: "Cameroun", en: "Cameroon", de: "Kamerun", continent: "AF" },
    { iso: "ca", fr: "Canada", en: "Canada", de: "Kanada", continent: "NA" },
    { iso: "cf", fr: "République centrafricaine", en: "Central African Republic", de: "Zentralafrikanische Republik", continent: "AF" },
    { iso: "td", fr: "Tchad", en: "Chad", de: "Tschad", continent: "AF" },
    { iso: "cl", fr: "Chili", en: "Chile", de: "Chile", continent: "SA" },
    { iso: "cn", fr: "Chine", en: "China", de: "China", continent: "AS" },
    { iso: "co", fr: "Colombie", en: "Colombia", de: "Kolumbien", continent: "SA" },
    { iso: "km", fr: "Comores", en: "Comoros", de: "Komoren", continent: "AF" },
    { iso: "cg", fr: "Congo", en: "Congo", de: "Kongo", continent: "AF" },
    { iso: "cd", fr: "République démocratique du Congo", en: "DR Congo", de: "Demokratische Republik Kongo", continent: "AF" },
    { iso: "cr", fr: "Costa Rica", en: "Costa Rica", de: "Costa Rica", continent: "NA" },
    { iso: "ci", fr: "Côte d'Ivoire", en: "Ivory Coast", de: "Elfenbeinküste", continent: "AF" },
    { iso: "hr", fr: "Croatie", en: "Croatia", de: "Kroatien", continent: "EU" },
    { iso: "cu", fr: "Cuba", en: "Cuba", de: "Kuba", continent: "NA" },
    { iso: "cy", fr: "Chypre", en: "Cyprus", de: "Zypern", continent: "EU" },
    { iso: "cz", fr: "Tchéquie", en: "Czech Republic", de: "Tschechien", continent: "EU" },
    { iso: "dk", fr: "Danemark", en: "Denmark", de: "Dänemark", continent: "EU" },
    { iso: "dj", fr: "Djibouti", en: "Djibouti", de: "Dschibuti", continent: "AF" },
    { iso: "dm", fr: "Dominique", en: "Dominica", de: "Dominica", continent: "NA" },
    { iso: "do", fr: "République dominicaine", en: "Dominican Republic", de: "Dominikanische Republik", continent: "NA" },
    { iso: "ec", fr: "Équateur", en: "Ecuador", de: "Ecuador", continent: "SA" },
    { iso: "eg", fr: "Égypte", en: "Egypt", de: "Ägypten", continent: "AF" },
    { iso: "sv", fr: "El Salvador", en: "El Salvador", de: "El Salvador", continent: "NA" },
    { iso: "gq", fr: "Guinée équatoriale", en: "Equatorial Guinea", de: "Äquatorialguinea", continent: "AF" },
    { iso: "er", fr: "Érythrée", en: "Eritrea", de: "Eritrea", continent: "AF" },
    { iso: "ee", fr: "Estonie", en: "Estonia", de: "Estland", continent: "EU" },
    { iso: "sz", fr: "Eswatini", en: "Eswatini", de: "Eswatini", continent: "AF" },
    { iso: "et", fr: "Éthiopie", en: "Ethiopia", de: "Äthiopien", continent: "AF" },
    { iso: "fj", fr: "Fidji", en: "Fiji", de: "Fidschi", continent: "OC" },
    { iso: "fi", fr: "Finlande", en: "Finland", de: "Finnland", continent: "EU" },
    { iso: "fr", fr: "France", en: "France", de: "Frankreich", continent: "EU" },
    { iso: "ga", fr: "Gabon", en: "Gabon", de: "Gabun", continent: "AF" },
    { iso: "gm", fr: "Gambie", en: "Gambia", de: "Gambia", continent: "AF" },
    { iso: "ge", fr: "Géorgie", en: "Georgia", de: "Georgien", continent: "AS" },
    { iso: "de", fr: "Allemagne", en: "Germany", de: "Deutschland", continent: "EU" },
    { iso: "gh", fr: "Ghana", en: "Ghana", de: "Ghana", continent: "AF" },
    { iso: "gr", fr: "Grèce", en: "Greece", de: "Griechenland", continent: "EU" },
    { iso: "gd", fr: "Grenade", en: "Grenada", de: "Grenada", continent: "NA" },
    { iso: "gt", fr: "Guatemala", en: "Guatemala", de: "Guatemala", continent: "NA" },
    { iso: "gn", fr: "Guinée", en: "Guinea", de: "Guinea", continent: "AF" },
    { iso: "gw", fr: "Guinée-Bissau", en: "Guinea-Bissau", de: "Guinea-Bissau", continent: "AF" },
    { iso: "gy", fr: "Guyana", en: "Guyana", de: "Guyana", continent: "SA" },
    { iso: "ht", fr: "Haïti", en: "Haiti", de: "Haiti", continent: "NA" },
    { iso: "hn", fr: "Honduras", en: "Honduras", de: "Honduras", continent: "NA" },
    { iso: "hu", fr: "Hongrie", en: "Hungary", de: "Ungarn", continent: "EU" },
    { iso: "is", fr: "Islande", en: "Iceland", de: "Island", continent: "EU" },
    { iso: "in", fr: "Inde", en: "India", de: "Indien", continent: "AS" },
    { iso: "id", fr: "Indonésie", en: "Indonesia", de: "Indonesien", continent: "AS" },
    { iso: "ir", fr: "Iran", en: "Iran", de: "Iran", continent: "AS" },
    { iso: "iq", fr: "Irak", en: "Iraq", de: "Irak", continent: "AS" },
    { iso: "ie", fr: "Irlande", en: "Ireland", de: "Irland", continent: "EU" },
    { iso: "il", fr: "Israël", en: "Israel", de: "Israel", continent: "AS" },
    { iso: "it", fr: "Italie", en: "Italy", de: "Italien", continent: "EU" },
    { iso: "jm", fr: "Jamaïque", en: "Jamaica", de: "Jamaika", continent: "NA" },
    { iso: "jp", fr: "Japon", en: "Japan", de: "Japan", continent: "AS" },
    { iso: "jo", fr: "Jordanie", en: "Jordan", de: "Jordanien", continent: "AS" },
    { iso: "kz", fr: "Kazakhstan", en: "Kazakhstan", de: "Kasachstan", continent: "AS" },
    { iso: "ke", fr: "Kenya", en: "Kenya", de: "Kenia", continent: "AF" },
    { iso: "ki", fr: "Kiribati", en: "Kiribati", de: "Kiribati", continent: "OC" },
    { iso: "kw", fr: "Koweït", en: "Kuwait", de: "Kuwait", continent: "AS" },
    { iso: "kg", fr: "Kirghizistan", en: "Kyrgyzstan", de: "Kirgisistan", continent: "AS" },
    { iso: "la", fr: "Laos", en: "Laos", de: "Laos", continent: "AS" },
    { iso: "lv", fr: "Lettonie", en: "Latvia", de: "Lettland", continent: "EU" },
    { iso: "lb", fr: "Liban", en: "Lebanon", de: "Libanon", continent: "AS" },
    { iso: "ls", fr: "Lesotho", en: "Lesotho", de: "Lesotho", continent: "AF" },
    { iso: "lr", fr: "Liberia", en: "Liberia", de: "Liberia", continent: "AF" },
    { iso: "ly", fr: "Libye", en: "Libya", de: "Libyen", continent: "AF" },
    { iso: "li", fr: "Liechtenstein", en: "Liechtenstein", de: "Liechtenstein", continent: "EU" },
    { iso: "lt", fr: "Lituanie", en: "Lithuania", de: "Litauen", continent: "EU" },
    { iso: "lu", fr: "Luxembourg", en: "Luxembourg", de: "Luxemburg", continent: "EU" },
    { iso: "mg", fr: "Madagascar", en: "Madagascar", de: "Madagaskar", continent: "AF" },
    { iso: "mw", fr: "Malawi", en: "Malawi", de: "Malawi", continent: "AF" },
    { iso: "my", fr: "Malaisie", en: "Malaysia", de: "Malaysia", continent: "AS" },
    { iso: "mv", fr: "Maldives", en: "Maldives", de: "Malediven", continent: "AS" },
    { iso: "ml", fr: "Mali", en: "Mali", de: "Mali", continent: "AF" },
    { iso: "mt", fr: "Malte", en: "Malta", de: "Malta", continent: "EU" },
    { iso: "mh", fr: "Marshall", en: "Marshall Islands", de: "Marshallinseln", continent: "OC" },
    { iso: "mr", fr: "Mauritanie", en: "Mauritania", de: "Mauretanien", continent: "AF" },
    { iso: "mu", fr: "Maurice", en: "Mauritius", de: "Mauritius", continent: "AF" },
    { iso: "mx", fr: "Mexique", en: "Mexico", de: "Mexiko", continent: "NA" },
    { iso: "fm", fr: "Micronésie", en: "Micronesia", de: "Mikronesien", continent: "OC" },
    { iso: "md", fr: "Moldavie", en: "Moldova", de: "Moldau", continent: "EU" },
    { iso: "mc", fr: "Monaco", en: "Monaco", de: "Monaco", continent: "EU" },
    { iso: "mn", fr: "Mongolie", en: "Mongolia", de: "Mongolei", continent: "AS" },
    { iso: "me", fr: "Monténégro", en: "Montenegro", de: "Montenegro", continent: "EU" },
    { iso: "ma", fr: "Maroc", en: "Morocco", de: "Marokko", continent: "AF" },
    { iso: "mz", fr: "Mozambique", en: "Mozambique", de: "Mosambik", continent: "AF" },
    { iso: "mm", fr: "Myanmar", en: "Myanmar", de: "Myanmar", continent: "AS" },
    { iso: "na", fr: "Namibie", en: "Namibia", de: "Namibia", continent: "AF" },
    { iso: "nr", fr: "Nauru", en: "Nauru", de: "Nauru", continent: "OC" },
    { iso: "np", fr: "Népal", en: "Nepal", de: "Nepal", continent: "AS" },
    { iso: "nl", fr: "Pays-Bas", en: "Netherlands", de: "Niederlande", continent: "EU" },
    { iso: "nz", fr: "Nouvelle-Zélande", en: "New Zealand", de: "Neuseeland", continent: "OC" },
    { iso: "ni", fr: "Nicaragua", en: "Nicaragua", de: "Nicaragua", continent: "NA" },
    { iso: "ne", fr: "Niger", en: "Niger", de: "Niger", continent: "AF" },
    { iso: "ng", fr: "Nigéria", en: "Nigeria", de: "Nigeria", continent: "AF" },
    { iso: "mk", fr: "Macédoine du Nord", en: "North Macedonia", de: "Nordmazedonien", continent: "EU" },
    { iso: "no", fr: "Norvège", en: "Norway", de: "Norwegen", continent: "EU" },
    { iso: "om", fr: "Oman", en: "Oman", de: "Oman", continent: "AS" },
    { iso: "pk", fr: "Pakistan", en: "Pakistan", de: "Pakistan", continent: "AS" },
    { iso: "pw", fr: "Palaos", en: "Palau", de: "Palau", continent: "OC" },
    { iso: "pa", fr: "Panama", en: "Panama", de: "Panama", continent: "NA" },
    { iso: "pg", fr: "Papouasie-Nouvelle-Guinée", en: "Papua New Guinea", de: "Papua-Neuguinea", continent: "OC" },
    { iso: "py", fr: "Paraguay", en: "Paraguay", de: "Paraguay", continent: "SA" },
    { iso: "pe", fr: "Pérou", en: "Peru", de: "Peru", continent: "SA" },
    { iso: "ph", fr: "Philippines", en: "Philippines", de: "Philippinen", continent: "AS" },
    { iso: "pl", fr: "Pologne", en: "Poland", de: "Polen", continent: "EU" },
    { iso: "pt", fr: "Portugal", en: "Portugal", de: "Portugal", continent: "EU" },
    { iso: "qa", fr: "Qatar", en: "Qatar", de: "Katar", continent: "AS" },
    { iso: "ro", fr: "Roumanie", en: "Romania", de: "Rumänien", continent: "EU" },
    { iso: "ru", fr: "Russie", en: "Russia", de: "Russland", continent: "EU" },
    { iso: "rw", fr: "Rwanda", en: "Rwanda", de: "Ruanda", continent: "AF" },
    { iso: "kn", fr: "Saint-Kitts-et-Nevis", en: "Saint Kitts and Nevis", de: "St. Kitts und Nevis", continent: "NA" },
    { iso: "lc", fr: "Sainte-Lucie", en: "Saint Lucia", de: "St. Lucia", continent: "NA" },
    { iso: "vc", fr: "Saint-Vincent-et-les-Grenadines", en: "Saint Vincent and the Grenadines", de: "St. Vincent und die Grenadinen", continent: "NA" },
    { iso: "ws", fr: "Samoa", en: "Samoa", de: "Samoa", continent: "OC" },
    { iso: "sm", fr: "Saint-Marin", en: "San Marino", de: "San Marino", continent: "EU" },
    { iso: "st", fr: "Sao Tomé-et-Principe", en: "Sao Tome and Principe", de: "São Tomé und Príncipe", continent: "AF" },
    { iso: "sa", fr: "Arabie saoudite", en: "Saudi Arabia", de: "Saudi-Arabien", continent: "AS" },
    { iso: "sn", fr: "Sénégal", en: "Senegal", de: "Senegal", continent: "AF" },
    { iso: "rs", fr: "Serbie", en: "Serbia", de: "Serbien", continent: "EU" },
    { iso: "sc", fr: "Seychelles", en: "Seychelles", de: "Seychellen", continent: "AF" },
    { iso: "sl", fr: "Sierra Leone", en: "Sierra Leone", de: "Sierra Leone", continent: "AF" },
    { iso: "sg", fr: "Singapour", en: "Singapore", de: "Singapur", continent: "AS" },
    { iso: "sk", fr: "Slovaquie", en: "Slovakia", de: "Slowakei", continent: "EU" },
    { iso: "si", fr: "Slovénie", en: "Slovenia", de: "Slowenien", continent: "EU" },
    { iso: "sb", fr: "Salomon", en: "Solomon Islands", de: "Salomonen", continent: "OC" },
    { iso: "so", fr: "Somalie", en: "Somalia", de: "Somalia", continent: "AF" },
    { iso: "za", fr: "Afrique du Sud", en: "South Africa", de: "Südafrika", continent: "AF" },
    { iso: "ss", fr: "Soudan du Sud", en: "South Sudan", de: "Südsudan", continent: "AF" },
    { iso: "es", fr: "Espagne", en: "Spain", de: "Spanien", continent: "EU" },
    { iso: "lk", fr: "Sri Lanka", en: "Sri Lanka", de: "Sri Lanka", continent: "AS" },
    { iso: "sd", fr: "Soudan", en: "Sudan", de: "Sudan", continent: "AF" },
    { iso: "sr", fr: "Suriname", en: "Suriname", de: "Suriname", continent: "SA" },
    { iso: "se", fr: "Suède", en: "Sweden", de: "Schweden", continent: "EU" },
    { iso: "ch", fr: "Suisse", en: "Switzerland", de: "Schweiz", continent: "EU" },
    { iso: "sy", fr: "Syrie", en: "Syria", de: "Syrien", continent: "AS" },
    { iso: "tw", fr: "Taïwan", en: "Taiwan", de: "Taiwan", continent: "AS" },
    { iso: "tj", fr: "Tadjikistan", en: "Tajikistan", de: "Tadschikistan", continent: "AS" },
    { iso: "tz", fr: "Tanzanie", en: "Tanzania", de: "Tansania", continent: "AF" },
    { iso: "th", fr: "Thaïlande", en: "Thailand", de: "Thailand", continent: "AS" },
    { iso: "tl", fr: "Timor oriental", en: "Timor-Leste", de: "Osttimor", continent: "AS" },
    { iso: "tg", fr: "Togo", en: "Togo", de: "Togo", continent: "AF" },
    { iso: "to", fr: "Tonga", en: "Tonga", de: "Tonga", continent: "OC" },
    { iso: "tt", fr: "Trinité-et-Tobago", en: "Trinidad and Tobago", de: "Trinidad und Tobago", continent: "NA" },
    { iso: "tn", fr: "Tunisie", en: "Tunisia", de: "Tunesien", continent: "AF" },
    { iso: "tr", fr: "Turquie", en: "Turkey", de: "Türkei", continent: "AS" },
    { iso: "tm", fr: "Turkménistan", en: "Turkmenistan", de: "Turkmenistan", continent: "AS" },
    { iso: "tv", fr: "Tuvalu", en: "Tuvalu", de: "Tuvalu", continent: "OC" },
    { iso: "ug", fr: "Ouganda", en: "Uganda", de: "Uganda", continent: "AF" },
    { iso: "ua", fr: "Ukraine", en: "Ukraine", de: "Ukraine", continent: "EU" },
    { iso: "ae", fr: "Émirats arabes unis", en: "United Arab Emirates", de: "Vereinigte Arabische Emirate", continent: "AS" },
    { iso: "gb", fr: "Royaume-Uni", en: "United Kingdom", de: "Vereinigtes Königreich", continent: "EU" },
    { iso: "us", fr: "États-Unis", en: "United States", de: "Vereinigte Staaten", continent: "NA" },
    { iso: "uy", fr: "Uruguay", en: "Uruguay", de: "Uruguay", continent: "SA" },
    { iso: "uz", fr: "Ouzbékistan", en: "Uzbekistan", de: "Usbekistan", continent: "AS" },
    { iso: "vu", fr: "Vanuatu", en: "Vanuatu", de: "Vanuatu", continent: "OC" },
    { iso: "ve", fr: "Venezuela", en: "Venezuela", de: "Venezuela", continent: "SA" },
    { iso: "vn", fr: "Vietnam", en: "Vietnam", de: "Vietnam", continent: "AS" },
    { iso: "ye", fr: "Yémen", en: "Yemen", de: "Jemen", continent: "AS" },
    { iso: "zm", fr: "Zambie", en: "Zambia", de: "Sambia", continent: "AF" },
    { iso: "zw", fr: "Zimbabwe", en: "Zimbabwe", de: "Simbabwe", continent: "AF" },
];

export const CONTINENTS = {
    "AF": { fr: "Afrique", en: "Africa", de: "Afrika" },
    "AS": { fr: "Asie", en: "Asia", de: "Asien" },
    "EU": { fr: "Europe", en: "Europe", de: "Europa" },
    "NA": { fr: "Amérique du Nord", en: "North America", de: "Nordamerika" },
    "SA": { fr: "Amérique du Sud", en: "South America", de: "Südamerika" },
    "OC": { fr: "Océanie", en: "Oceania", de: "Ozeanien" },
};